name: my first workflow
on: [push,fork]

jobs:
  first_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: Welcome message
      run: |
        echo "this is my first github actions"
        ls -ltra
        cat README.md
        echo "this is my first github actions"
        sudo apt-get install cowsay -y
        

    
    - name: generate ASCII Artwork
      run: cowsay -f dragon "run for cover,i am a dragon .... rawr ">>dragon.txt

    - name: test file
      run: grep -i "dragon" dragon.txt

    - name: upload file
      run: cat dragon.txt

      
    # - name: list files
    #   run: ls

    # - name: read file
    #   run: cat README.md 